'use client';

import { FormEvent, ReactNode, useState } from 'react';

type Role='super_admin'|'employee'|'manager'|'finance'|'owner'|'cashier';
type OrganizationItem={id:string;kind:string;name:string;detail:string;openingBalance:number;status:string;createdAt:string;updatedAt:string};
type Invoice={id:string;kind:string;invoiceNumber:string;counterparty:string;amount:number;issueDate:string;dueDate:string;status:string;note:string};
type PaymentPlan={id:string;kind:string;subject:string;counterparty:string;amount:number;dueDate:string;status:string;note:string};
type BankRow={id:string;accountId:string;occurredOn:string;description:string;amount:number;balance:number|null;reference:string;status:string;transactionId:string|null};
type Notice={id:string;title:string;message:string;kind:string;readAt:string|null;createdAt:string};
type AuditLog={id:string;userName:string;action:string;entityType:string;entityId:string;detail:string;createdAt:string};
type DeletedRecord={id:string;entityType:string;entityId:string;label:string;deletedByName:string;deletedAt:string};
type Backup={id:string;kind:string;size:number;createdBy:string;createdAt:string};
type Transaction={id:string;type:'income'|'expense';subject:string;counterparty:string;amount:number;note:string;status:string;createdBy:string;accountId:string|null;departmentId:string|null;projectId:string|null;categoryId:string|null;createdAt:string;attachmentCount:number};
type Settings={emailConfigured:boolean;wechatConfigured:boolean;dingtalkConfigured:boolean;emailEnabled:boolean;wechatEnabled:boolean;dingtalkEnabled:boolean;updatedAt:string}|null;
type NotificationDelivery={id:string;channel:string;title:string;message:string;status:string;responseCode:number|null;error:string;sourceKind:string;createdAt:string;sentAt:string|null};
type DailyRun={id:string;jobName:string;runDate:string;status:string;detail:string;startedAt:string;completedAt:string|null};
export type AdvancedData={companyName:string;currentUser:{id:string;name:string;role:Role};organizationItems:OrganizationItem[];invoices:Invoice[];paymentPlans:PaymentPlan[];bankRows:BankRow[];notifications:Notice[];notificationSettings:Settings;auditLogs:AuditLog[];deletedRecords:DeletedRecord[];backups:Backup[];transactions:Transaction[];notificationDeliveries:NotificationDelivery[];dailyRuns:DailyRun[]};

const money=(value:number)=>`¥ ${value.toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const dateText=(value:string)=>value?new Date(value).toLocaleString('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';
const kindNames:Record<string,string>={bank:'银行账户',cash:'现金账户',department:'部门',project:'项目',income_category:'收入类别',expense_category:'费用类别'};
const statusNames:Record<string,string>={unpaid:'未收付',partial:'部分收付',paid:'已收付',void:'已作废',pending:'待处理',completed:'已完成',overdue:'已逾期',cancelled:'已取消',matched:'已对账',unmatched:'未匹配'};

async function call<T=Record<string,unknown>>(url:string,options?:RequestInit):Promise<T>{const response=await fetch(url,options);const data=await response.json().catch(()=>({})) as T&{error?:string};if(!response.ok)throw new Error(data.error??'操作失败');return data}

export default function AdvancedPages({page,data,reload,flash}:{page:'finance'|'settings'|'security'|'notifications';data:AdvancedData;reload:()=>Promise<void>;flash:(text:string)=>void}){
  const [busy,setBusy]=useState(false);const [financeTab,setFinanceTab]=useState<'invoice'|'plan'|'bank'|'monthly'>('invoice');const [editingItem,setEditingItem]=useState<OrganizationItem|null>(null);
  const run=async(task:()=>Promise<unknown>,success:string)=>{setBusy(true);try{await task();await reload();flash(success)}catch(error){flash(error instanceof Error?error.message:'操作失败')}finally{setBusy(false)}};

  async function saveCompany(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await run(()=>call('/api/settings',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({entity:'company',companyName:String(form.get('companyName'))})}),'公司名称已更新')}
  async function saveItem(event:FormEvent<HTMLFormElement>){event.preventDefault();const element=event.currentTarget;const form=new FormData(element);const body={id:editingItem?.id,kind:String(form.get('kind')),name:String(form.get('name')),detail:String(form.get('detail')),openingBalance:Number(form.get('openingBalance')??0)};await run(()=>call('/api/settings',{method:editingItem?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),editingItem?'基础参数已修改':'基础参数已添加');setEditingItem(null);element.reset()}
  async function removeItem(item:OrganizationItem){if(!confirm(`确定删除“${item.name}”吗？删除后可在回收站恢复。`))return;await run(()=>call(`/api/settings?id=${encodeURIComponent(item.id)}`,{method:'DELETE'}),'已移入回收站')}
  async function saveInvoice(event:FormEvent<HTMLFormElement>){event.preventDefault();const element=event.currentTarget;const form=new FormData(element);const body={entity:'invoice',kind:String(form.get('kind')),invoiceNumber:String(form.get('invoiceNumber')),counterparty:String(form.get('counterparty')),amount:Number(form.get('amount')),issueDate:String(form.get('issueDate')),dueDate:String(form.get('dueDate')),note:String(form.get('note'))};await run(()=>call('/api/finance',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),'发票已登记');element.reset()}
  async function savePlan(event:FormEvent<HTMLFormElement>){event.preventDefault();const element=event.currentTarget;const form=new FormData(element);const body={entity:'plan',kind:String(form.get('kind')),subject:String(form.get('subject')),counterparty:String(form.get('counterparty')),amount:Number(form.get('amount')),dueDate:String(form.get('dueDate')),note:String(form.get('note'))};await run(()=>call('/api/finance',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),'收付款计划已添加');element.reset()}
  async function updateFinance(entity:'invoice'|'plan',id:string,status:string){await run(()=>call('/api/finance',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({entity,id,status})}),'状态已更新')}
  async function removeFinance(entity:'invoice'|'plan',id:string){if(!confirm('确定删除吗？删除后可在回收站恢复。'))return;await run(()=>call(`/api/finance?entity=${entity}&id=${encodeURIComponent(id)}`,{method:'DELETE'}),'已移入回收站')}
  async function importBank(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const file=form.get('file');if(!(file instanceof File))return;const text=await file.text();const lines=parseCsv(text);if(lines.length<2){flash('CSV 文件没有有效数据');return}const headers=lines[0].map((value)=>value.trim().toLowerCase());const index=(...names:string[])=>headers.findIndex((header)=>names.includes(header));const dateIndex=index('date','日期','交易日期');const descriptionIndex=index('description','摘要','交易摘要');const amountIndex=index('amount','金额','交易金额');const balanceIndex=index('balance','余额');const referenceIndex=index('reference','流水号','参考号');if(dateIndex<0||descriptionIndex<0||amountIndex<0){flash('CSV 必须包含日期、摘要、金额三列');return}const rows=lines.slice(1).filter((row)=>row.some(Boolean)).map((row)=>({date:row[dateIndex],description:row[descriptionIndex],amount:Number(String(row[amountIndex]).replaceAll(',','')),balance:balanceIndex>=0?Number(String(row[balanceIndex]).replaceAll(',','')):null,reference:referenceIndex>=0?row[referenceIndex]:''}));await run(()=>call('/api/finance',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({entity:'bank_import',accountId:String(form.get('accountId')),rows})}),`已导入 ${rows.length} 条银行流水`);event.currentTarget.reset()}
  async function autoReconcile(){const result=await call<{matched:number}>('/api/finance',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({entity:'auto_reconcile'})});await reload();flash(`自动匹配 ${result.matched} 条流水`)}
  async function securityAction(action:string,id?:string){if((action==='restore_backup'||action==='delete_forever')&&!confirm(action==='restore_backup'?'恢复会用备份覆盖当前业务数据，系统会先自动保留恢复前备份。确定继续吗？':'永久删除后无法恢复，确定继续吗？'))return;await run(()=>call('/api/security',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,id})}),action==='backup'?'备份已创建':action==='restore_backup'?'备份已恢复':action==='restore_deleted'?'记录已恢复':'记录已永久删除')}
  async function saveNotificationSettings(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const body={action:'settings',email_webhook:String(form.get('emailWebhook')),wechat_webhook:String(form.get('wechatWebhook')),dingtalk_webhook:String(form.get('dingtalkWebhook')),emailEnabled:form.get('emailEnabled')==='on',wechatEnabled:form.get('wechatEnabled')==='on',dingtalkEnabled:form.get('dingtalkEnabled')==='on'};await run(()=>call('/api/notifications',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),'通知配置已保存')}
  async function markRead(id='all'){await call('/api/notifications',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id})});await reload()}

  if(page==='settings')return <SettingsPage/>;
  if(page==='security')return <SecurityPage/>;
  if(page==='notifications')return <NotificationsPage/>;
  return <FinancePage/>;

  function SettingsPage(){const grouped=Object.entries(kindNames).map(([kind,label])=>({kind,label,items:data.organizationItems.filter((item)=>item.kind===kind)}));return <div className="advanced-stack"><section className="panel"><div className="section-actions"><div><h2>公司基础资料</h2><p>仅陈泽宇超级管理员可以修改</p></div></div><form className="inline-form" onSubmit={saveCompany}><label>公司名称<input name="companyName" defaultValue={data.companyName} required maxLength={100}/></label><button disabled={busy}>保存名称</button></form></section><section className="panel"><div className="section-actions"><div><h2>基础参数</h2><p>银行、现金、部门、项目和收支类别统一维护</p></div></div><form className="config-form" key={editingItem?.id??'new'} onSubmit={saveItem}><label>参数类型<select name="kind" defaultValue={editingItem?.kind??'bank'}>{Object.entries(kindNames).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>名称<input name="name" defaultValue={editingItem?.name} required maxLength={80}/></label><label>账号 / 说明<input name="detail" defaultValue={editingItem?.detail} maxLength={200} placeholder="银行名称、尾号或补充说明"/></label><label>期初余额<input name="openingBalance" type="number" step="0.01" defaultValue={editingItem?.openingBalance??0}/></label><div className="config-actions">{editingItem?<button type="button" onClick={()=>setEditingItem(null)}>取消编辑</button>:null}<button className="primary-button" disabled={busy}>{editingItem?'保存修改':'添加参数'}</button></div></form><div className="config-groups">{grouped.map((group)=><article key={group.kind}><h3>{group.label}<span>{group.items.length}</span></h3>{group.items.map((item)=><div key={item.id}><span><strong>{item.name}</strong><small>{item.detail||'无补充说明'}{['bank','cash'].includes(item.kind)?` · 期初 ${money(item.openingBalance)}`:''}</small></span><button onClick={()=>setEditingItem(item)}>修改</button><button className="danger" onClick={()=>void removeItem(item)}>删除</button></div>)}{group.items.length===0?<p>暂未添加</p>:null}</article>)}</div></section></div>}

  function FinancePage(){const openInvoice=data.invoices.filter((item)=>!['paid','void'].includes(item.status));const pendingPlans=data.paymentPlans.filter((item)=>item.status==='pending');const unmatched=data.bankRows.filter((item)=>item.status==='unmatched');const month=new Date().toISOString().slice(0,7);const monthRows=data.transactions.filter((item)=>item.createdAt.startsWith(month)&&item.status!=='已驳回');const income=monthRows.filter((item)=>item.type==='income').reduce((sum,item)=>sum+item.amount,0);const expense=monthRows.filter((item)=>item.type==='expense').reduce((sum,item)=>sum+item.amount,0);return <div className="advanced-stack"><section className="metrics"><article className="metric-card income"><div className="metric-head"><span>未结发票</span><i/></div><strong>{money(openInvoice.reduce((sum,item)=>sum+item.amount,0))}</strong><small>{openInvoice.length} 张</small></article><article className="metric-card expense"><div className="metric-head"><span>待执行计划</span><i/></div><strong>{money(pendingPlans.reduce((sum,item)=>sum+item.amount,0))}</strong><small>{pendingPlans.length} 笔</small></article><article className="metric-card pending"><div className="metric-head"><span>未对账流水</span><i/></div><strong>{unmatched.length} 条</strong><small>等待自动或人工匹配</small></article><article className="metric-card balance"><div className="metric-head"><span>本月净收支</span><i/></div><strong>{money(income-expense)}</strong><small>收入 {money(income)} · 支出 {money(expense)}</small></article></section><section className="panel"><div className="tool-tabs">{([['invoice','发票管理'],['plan','收付款计划'],['bank','银行对账'],['monthly','月度统计']] as const).map(([key,label])=><button key={key} className={financeTab===key?'active':''} onClick={()=>setFinanceTab(key)}>{label}</button>)}</div>{financeTab==='invoice'?<InvoicePanel/>:financeTab==='plan'?<PlanPanel/>:financeTab==='bank'?<BankPanel/>:<MonthlyPanel/>}</section></div>}

  function InvoicePanel(){return <><form className="config-form finance-form" onSubmit={saveInvoice}><label>发票类型<select name="kind"><option value="receivable">销项 / 应收</option><option value="payable">进项 / 应付</option></select></label><label>发票号码<input name="invoiceNumber" required/></label><label>往来单位<input name="counterparty" required/></label><label>金额<input name="amount" type="number" min="0.01" step="0.01" required/></label><label>开票日期<input name="issueDate" type="date" required/></label><label>到期日期<input name="dueDate" type="date"/></label><label className="span-two">备注<input name="note"/></label><div className="config-actions"><button className="primary-button" disabled={busy}>登记发票</button></div></form><DataTable headers={['号码','类型','单位','金额','日期/到期','状态','操作']}>{data.invoices.map((item)=><tr key={item.id}><td>{item.invoiceNumber}</td><td>{item.kind==='receivable'?'应收':'应付'}</td><td>{item.counterparty}</td><td>{money(item.amount)}</td><td>{item.issueDate}<small>{item.dueDate||'无到期日'}</small></td><td><Status value={statusNames[item.status]??item.status}/></td><td><div className="row-actions"><button onClick={()=>void updateFinance('invoice',item.id,'paid')}>已收付</button><button className="danger" onClick={()=>void removeFinance('invoice',item.id)}>删除</button></div></td></tr>)}</DataTable></>}
  function PlanPanel(){return <><form className="config-form finance-form" onSubmit={savePlan}><label>计划类型<select name="kind"><option value="payable">付款计划</option><option value="receivable">收款计划</option></select></label><label>事项<input name="subject" required/></label><label>往来单位<input name="counterparty" required/></label><label>金额<input name="amount" type="number" min="0.01" step="0.01" required/></label><label>到期日期<input name="dueDate" type="date" required/></label><label>备注<input name="note"/></label><div className="config-actions"><button className="primary-button" disabled={busy}>添加计划</button></div></form><DataTable headers={['事项','类型','单位','金额','到期日','状态','操作']}>{data.paymentPlans.map((item)=><tr key={item.id}><td><strong>{item.subject}</strong></td><td>{item.kind==='receivable'?'收款':'付款'}</td><td>{item.counterparty}</td><td>{money(item.amount)}</td><td>{item.dueDate}</td><td><Status value={statusNames[item.status]??item.status}/></td><td><div className="row-actions"><button onClick={()=>void updateFinance('plan',item.id,'completed')}>完成</button><button className="danger" onClick={()=>void removeFinance('plan',item.id)}>删除</button></div></td></tr>)}</DataTable></>}
  function BankPanel(){const accounts=data.organizationItems.filter((item)=>['bank','cash'].includes(item.kind));return <><div className="bank-actions"><form onSubmit={importBank}><select name="accountId" required defaultValue=""><option value="" disabled>选择银行或现金账户</option>{accounts.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select><input name="file" type="file" accept=".csv,text/csv" required/><button className="primary-button" disabled={busy}>导入 CSV</button></form><button onClick={()=>void autoReconcile()}>自动对账</button><small>CSV 表头支持：日期、摘要、金额、余额、流水号</small></div><DataTable headers={['日期','账户','摘要','金额','余额','状态','匹配单据']}>{data.bankRows.map((item)=><tr key={item.id}><td>{item.occurredOn}</td><td>{accounts.find((account)=>account.id===item.accountId)?.name??'未知账户'}</td><td>{item.description}</td><td className={item.amount>=0?'amount-in':'amount-out'}>{money(item.amount)}</td><td>{item.balance==null?'—':money(item.balance)}</td><td><Status value={statusNames[item.status]??item.status}/></td><td>{item.transactionId??'—'}</td></tr>)}</DataTable></>}
  function MonthlyPanel(){const map=new Map<string,{income:number;expense:number;count:number}>();for(const item of data.transactions){if(item.status==='已驳回')continue;const key=item.createdAt.slice(0,7);const row=map.get(key)??{income:0,expense:0,count:0};row[item.type]+=item.amount;row.count+=1;map.set(key,row)}const monthly=Array.from(map.entries()).sort(([a],[b])=>b.localeCompare(a)).slice(0,12);const categories=data.organizationItems.filter((item)=>item.kind.endsWith('_category'));const opening=data.organizationItems.filter((item)=>['bank','cash'].includes(item.kind)).reduce((sum,item)=>sum+item.openingBalance,0);const allIncome=data.transactions.filter((item)=>item.status!=='已驳回'&&item.type==='income').reduce((sum,item)=>sum+item.amount,0);const allExpense=data.transactions.filter((item)=>item.status!=='已驳回'&&item.type==='expense').reduce((sum,item)=>sum+item.amount,0);return <div className="monthly-grid"><article><h3>近 12 个月收支</h3><div className="monthly-row"><strong>当前余额</strong><span>期初 {money(opening)}</span><span>累计净收支 {money(allIncome-allExpense)}</span><b>{money(opening+allIncome-allExpense)}</b></div>{monthly.map(([month,row])=><div className="monthly-row" key={month}><strong>{month}</strong><span className="amount-in">收入 {money(row.income)}</span><span>支出 {money(row.expense)}</span><b>{money(row.income-row.expense)}</b></div>)}{monthly.length===0?<p className="muted">暂无月度数据</p>:null}</article><article><h3>收支分类</h3>{categories.map((item)=><div className="category-row" key={item.id}><span>{item.kind==='income_category'?'收入':'支出'}</span><strong>{item.name}</strong><small>{item.detail||'—'}</small></div>)}{categories.length===0?<p className="muted">请先到系统设置中添加收入或费用类别</p>:null}</article></div>}

  function SecurityPage(){return <div className="advanced-stack"><section className="panel"><div className="section-actions"><div><h2>数据备份与恢复</h2><p>系统每天 00:05 自动备份并记录执行结果，也可随时手动备份</p></div><button className="primary-button" disabled={busy} onClick={()=>void securityAction('backup')}>立即备份</button></div><DataTable headers={['运行日期','状态','执行结果','开始时间']}>{data.dailyRuns.map((item)=><tr key={item.id}><td>{item.runDate}</td><td><Status value={item.status==='completed'?'已完成':item.status==='failed'?'失败':'执行中'}/></td><td>{item.detail||'—'}</td><td>{dateText(item.startedAt)}</td></tr>)}</DataTable><div className="backup-list">{data.backups.map((item)=><article key={item.id}><span><strong>{item.kind==='automatic'?'自动备份':item.kind==='pre_restore'?'恢复前备份':'手动备份'}</strong><small>{dateText(item.createdAt)} · {(item.size/1024).toFixed(1)} KB</small></span><a href={`/api/security?backup=${encodeURIComponent(item.id)}`}>下载</a><button onClick={()=>void securityAction('restore_backup',item.id)}>恢复</button></article>)}</div></section><section className="panel"><div className="section-actions"><div><h2>回收站</h2><p>删除的单据、附件、人员和参数可在这里恢复</p></div></div><DataTable headers={['类型','名称','删除人','删除时间','操作']}>{data.deletedRecords.map((item)=><tr key={item.id}><td>{item.entityType}</td><td><strong>{item.label}</strong><small>{item.entityId}</small></td><td>{item.deletedByName}</td><td>{dateText(item.deletedAt)}</td><td><div className="row-actions"><button onClick={()=>void securityAction('restore_deleted',item.id)}>恢复</button><button className="danger" onClick={()=>void securityAction('delete_forever',item.id)}>永久删除</button></div></td></tr>)}</DataTable></section><section className="panel"><div className="section-actions"><div><h2>操作日志</h2><p>记录关键新增、修改、审批、删除和恢复操作</p></div></div><DataTable headers={['操作人','动作','对象','详情','时间']}>{data.auditLogs.map((item)=><tr key={item.id}><td>{item.userName}</td><td>{item.action}</td><td>{item.entityType}<small>{item.entityId}</small></td><td>{item.detail||'—'}</td><td>{dateText(item.createdAt)}</td></tr>)}</DataTable></section></div>}

  function NotificationsPage(){const unread=data.notifications.filter((item)=>!item.readAt).length;return <div className="approval-layout"><section className="panel"><div className="section-actions"><div><h2>站内消息</h2><p>{unread} 条未读消息</p></div>{unread?<button onClick={()=>void markRead()}>全部已读</button>:null}</div><div className="notice-list">{data.notifications.map((item)=><button key={item.id} className={item.readAt?'read':''} onClick={()=>void markRead(item.id)}><i/><span><strong>{item.title}</strong><p>{item.message}</p><small>{dateText(item.createdAt)}</small></span></button>)}{data.notifications.length===0?<p className="muted">暂无消息</p>:null}</div></section>{data.currentUser.role==='super_admin'?<><section className="panel"><div className="section-actions"><div><h2>外部通知配置</h2><p>支持邮件自动化 Webhook、企业微信与钉钉机器人</p></div></div><form className="notification-form" onSubmit={saveNotificationSettings}><label><span>邮件通知 Webhook</span><input name="emailWebhook" type="url" placeholder={data.notificationSettings?.emailConfigured?'已配置，留空保持不变':'https://...'}/><input name="emailEnabled" type="checkbox" defaultChecked={data.notificationSettings?.emailEnabled}/>启用</label><label><span>企业微信机器人</span><input name="wechatWebhook" type="url" placeholder={data.notificationSettings?.wechatConfigured?'已配置，留空保持不变':'https://qyapi.weixin.qq.com/...'}/><input name="wechatEnabled" type="checkbox" defaultChecked={data.notificationSettings?.wechatEnabled}/>启用</label><label><span>钉钉机器人</span><input name="dingtalkWebhook" type="url" placeholder={data.notificationSettings?.dingtalkConfigured?'已配置，留空保持不变':'https://oapi.dingtalk.com/...'}/><input name="dingtalkEnabled" type="checkbox" defaultChecked={data.notificationSettings?.dingtalkEnabled}/>启用</label><div className="notification-actions"><button type="button" onClick={()=>void run(()=>call('/api/notifications',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'test'})}),'测试消息已发送并记录结果')}>发送测试</button><button className="primary-button" disabled={busy}>保存配置</button></div></form></section><section className="panel"><div className="section-actions"><div><h2>通知发送记录</h2><p>每次邮件、企业微信和钉钉发送结果都会保留</p></div></div><DataTable headers={['渠道','标题','状态','返回码 / 错误','发送时间']}>{data.notificationDeliveries.map((item)=><tr key={item.id}><td>{item.channel==='email'?'邮件':item.channel==='wechat'?'企业微信':'钉钉'}</td><td><strong>{item.title}</strong><small>{item.message}</small></td><td><Status value={item.status==='sent'?'已发送':item.status==='failed'?'失败':'发送中'}/></td><td>{item.responseCode??(item.error||'—')}</td><td>{dateText(item.sentAt??item.createdAt)}</td></tr>)}</DataTable></section></>:null}</div>}
}

function DataTable({headers,children}:{headers:string[];children:ReactNode}){return <div className="table-wrap advanced-table"><table><thead><tr>{headers.map((header)=><th key={header}>{header}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
function Status({value}:{value:string}){return <span className={`status status-${value}`}>{value}</span>}

function parseCsv(text:string){const rows:string[][]=[];let row:string[]=[];let cell='';let quoted=false;for(let index=0;index<text.length;index+=1){const character=text[index];if(character==='"'){if(quoted&&text[index+1]==='"'){cell+='"';index+=1}else quoted=!quoted}else if(character===','&&!quoted){row.push(cell);cell=''}else if((character==='\n'||character==='\r')&&!quoted){if(character==='\r'&&text[index+1]==='\n')index+=1;row.push(cell);if(row.some((value)=>value.trim()))rows.push(row);row=[];cell=''}else cell+=character}row.push(cell);if(row.some((value)=>value.trim()))rows.push(row);return rows}
