import { env } from 'cloudflare:workers';
import { createBackup, restoreBackup } from '../../lib/backup';
import { errorResponse, requireAppUser, requireRole, writeAudit } from '../../lib/server';

async function restoreDeletedRecord(record:Record<string,unknown>){
  const entity=String(record.entity_type);const parsed=JSON.parse(String(record.record_json)) as Record<string,unknown>;
  if(entity==='organization_item')await env.DB.prepare('INSERT OR REPLACE INTO organization_items (id,kind,name,detail,opening_balance_cents,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)').bind(parsed.id,parsed.kind,parsed.name,parsed.detail,parsed.opening_balance_cents,parsed.status,parsed.created_at,parsed.updated_at).run();
  else if(entity==='invoice')await env.DB.prepare('INSERT OR REPLACE INTO invoices (id,kind,invoice_number,counterparty,amount_cents,issue_date,due_date,status,transaction_id,note,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(parsed.id,parsed.kind,parsed.invoice_number,parsed.counterparty,parsed.amount_cents,parsed.issue_date,parsed.due_date,parsed.status,parsed.transaction_id,parsed.note,parsed.created_by,parsed.created_at,parsed.updated_at).run();
  else if(entity==='payment_plan')await env.DB.prepare('INSERT OR REPLACE INTO payment_plans (id,kind,subject,counterparty,amount_cents,due_date,status,invoice_id,note,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)').bind(parsed.id,parsed.kind,parsed.subject,parsed.counterparty,parsed.amount_cents,parsed.due_date,parsed.status,parsed.invoice_id,parsed.note,parsed.created_by,parsed.created_at,parsed.updated_at).run();
  else if(entity==='partner')await env.DB.prepare('INSERT OR REPLACE INTO partners (id,name,kind,contact,phone,note,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)').bind(parsed.id,parsed.name,parsed.kind,parsed.contact,parsed.phone,parsed.note,parsed.created_at,parsed.updated_at).run();
  else if(entity==='attachment')await env.DB.prepare('INSERT OR REPLACE INTO attachments (id,transaction_id,file_key,filename,content_type,size,uploaded_by,created_at) VALUES (?,?,?,?,?,?,?,?)').bind(parsed.id,parsed.transaction_id,parsed.file_key,parsed.filename,parsed.content_type,parsed.size,parsed.uploaded_by,parsed.created_at).run();
  else if(entity==='user')await env.DB.prepare('INSERT OR REPLACE INTO app_users (id,auth_user_id,email,name,role,status,password_hash,password_salt,must_change_password,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)').bind(parsed.id,parsed.auth_user_id,parsed.email,parsed.name,parsed.role,parsed.status,parsed.password_hash,parsed.password_salt,parsed.must_change_password,parsed.created_at,parsed.updated_at).run();
  else if(entity==='transaction'){
    const transaction=parsed.transaction as Record<string,unknown>;await env.DB.prepare('INSERT OR REPLACE INTO transactions (id,type,subject,counterparty,amount_cents,note,status,created_by,created_at) VALUES (?,?,?,?,?,?,?,?,?)').bind(transaction.id,transaction.type,transaction.subject,transaction.counterparty,transaction.amount_cents,transaction.note,transaction.status,transaction.created_by,transaction.created_at).run();
    const approvals=Array.isArray(parsed.approvals)?parsed.approvals as Record<string,unknown>[]:[];const attachments=Array.isArray(parsed.attachments)?parsed.attachments as Record<string,unknown>[]:[];
    if(approvals.length)await env.DB.batch(approvals.map((row)=>env.DB.prepare('INSERT OR REPLACE INTO approvals (id,transaction_id,stage,action,actor_id,actor_name,comment,created_at) VALUES (?,?,?,?,?,?,?,?)').bind(row.id,row.transaction_id,row.stage,row.action,row.actor_id,row.actor_name,row.comment,row.created_at)));
    if(attachments.length)await env.DB.batch(attachments.map((row)=>env.DB.prepare('INSERT OR REPLACE INTO attachments (id,transaction_id,file_key,filename,content_type,size,uploaded_by,created_at) VALUES (?,?,?,?,?,?,?,?)').bind(row.id,row.transaction_id,row.file_key,row.filename,row.content_type,row.size,row.uploaded_by,row.created_at)));
  } else throw new Response(JSON.stringify({error:'该类型暂不支持恢复'}),{status:400,headers:{'content-type':'application/json'}});
}

export async function POST(request:Request){
  try{const user=await requireAppUser();requireRole(user,['super_admin']);const body=await request.json() as Record<string,unknown>;const action=String(body.action??'');
    if(action==='backup'){const item=await createBackup(user,'manual');return Response.json({item})}
    if(action==='restore_backup'){const id=String(body.id??'');await restoreBackup(user,id);return Response.json({ok:true})}
    if(action==='restore_deleted'){const id=String(body.id??'');const record=await env.DB.prepare('SELECT * FROM deleted_records WHERE id=?').bind(id).first<Record<string,unknown>>();if(!record)return Response.json({error:'回收站记录不存在'},{status:404});await restoreDeletedRecord(record);await env.DB.prepare('DELETE FROM deleted_records WHERE id=?').bind(id).run();await writeAudit(user,'恢复删除记录',String(record.entity_type),String(record.entity_id),String(record.label));return Response.json({ok:true})}
    if(action==='delete_forever'){const id=String(body.id??'');const record=await env.DB.prepare('SELECT * FROM deleted_records WHERE id=?').bind(id).first<Record<string,unknown>>();if(!record)return Response.json({error:'回收站记录不存在'},{status:404});const parsed=JSON.parse(String(record.record_json)) as Record<string,unknown>&{attachments?:Record<string,unknown>[]};if(record.entity_type==='transaction')await Promise.all((parsed.attachments??[]).map((file)=>env.FILES.delete(String(file.file_key))));if(record.entity_type==='attachment'&&parsed.file_key)await env.FILES.delete(String(parsed.file_key));await env.DB.prepare('DELETE FROM deleted_records WHERE id=?').bind(id).run();await writeAudit(user,'永久删除',String(record.entity_type),String(record.entity_id),String(record.label));return Response.json({ok:true})}
    return Response.json({error:'不支持的安全操作'},{status:400});
  }catch(error){return errorResponse(error)}
}

export async function GET(request:Request){
  try{const user=await requireAppUser();requireRole(user,['super_admin']);const id=new URL(request.url).searchParams.get('backup');if(!id)return Response.json({error:'缺少备份编号'},{status:400});const row=await env.DB.prepare('SELECT file_key,created_at FROM backups WHERE id=?').bind(id).first<Record<string,unknown>>();if(!row)return Response.json({error:'备份不存在'},{status:404});const object=await env.FILES.get(String(row.file_key));if(!object)return Response.json({error:'备份文件不存在'},{status:404});return new Response(object.body,{headers:{'content-type':'application/json','content-disposition':`attachment; filename="hengzhang-backup-${String(row.created_at).slice(0,10)}.json"`}})}catch(error){return errorResponse(error)}
}
